# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ayxtk/chiplab/IP/myCPU/IP/data_bank_sram/data_bank_sram.xci
# IP: The module: 'data_bank_sram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ayxtk/chiplab/IP/myCPU/IP/data_bank_sram/data_bank_sram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_bank_sram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/ayxtk/chiplab/IP/myCPU/IP/data_bank_sram/data_bank_sram.xci
# IP: The module: 'data_bank_sram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ayxtk/chiplab/IP/myCPU/IP/data_bank_sram/data_bank_sram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'data_bank_sram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
