# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ayxtk/chiplab/IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux.xci
# IP: The module: 'axi_2x1_mux' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ayxtk/chiplab/IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux_impl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_2x1_mux'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ayxtk/chiplab/IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_2x1_mux'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ayxtk/chiplab/IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_2x1_mux'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/ayxtk/chiplab/IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux.xci
# IP: The module: 'axi_2x1_mux' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ayxtk/chiplab/IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux_impl_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_2x1_mux'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ayxtk/chiplab/IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_2x1_mux'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/ayxtk/chiplab/IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_2x1_mux'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
