# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/ayxtk/chiplab/IP/xilinx_ip/2023.2/dpram_512x32/dpram_512x32.xci
# IP: The module: 'dpram_512x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ayxtk/chiplab/IP/xilinx_ip/2023.2/dpram_512x32/dpram_512x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram_512x32'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/ayxtk/chiplab/IP/xilinx_ip/2023.2/dpram_512x32/dpram_512x32.xci
# IP: The module: 'dpram_512x32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/ayxtk/chiplab/IP/xilinx_ip/2023.2/dpram_512x32/dpram_512x32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dpram_512x32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
