# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_3/soc_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_3" START { ROLLUP_AUTO }
set_param general.usePosixSpawnForFork 1
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a200tfbg676-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.cache/wt [current_project]
set_property parent.project_path /home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog {
  /home/lch/work/miracle/chiplab/IP/myCPU/csr.h
  /home/lch/work/miracle/chiplab/chip/soc_demo/loongson/config.h
  /home/lch/work/miracle/chiplab/IP/myCPU/mycpu.h
  /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_defines.h
}
set_property file_type "Verilog Header" [get_files /home/lch/work/miracle/chiplab/IP/myCPU/csr.h]
set_property file_type "Verilog Header" [get_files /home/lch/work/miracle/chiplab/chip/soc_demo/loongson/config.h]
set_property file_type "Verilog Header" [get_files /home/lch/work/miracle/chiplab/IP/myCPU/mycpu.h]
set_property file_type "Verilog Header" [get_files /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_defines.h]
read_verilog -library xil_defaultlib {
  /home/lch/work/miracle/chiplab/IP/myCPU/addr_trans.v
  /home/lch/work/miracle/chiplab/IP/myCPU/alu.v
  /home/lch/work/miracle/chiplab/IP/APB_DEV/apb_dev_top_with_nand.v
  /home/lch/work/miracle/chiplab/IP/APB_DEV/apb_mux2.v
  /home/lch/work/miracle/chiplab/IP/AMBA/axi2apb.v
  /home/lch/work/miracle/chiplab/IP/myCPU/axi_bridge.v
  /home/lch/work/miracle/chiplab/IP/AXI/axi_interconnect_0.v
  /home/lch/work/miracle/chiplab/IP/AMBA/axi_mux_syn.v
  /home/lch/work/miracle/chiplab/IP/MAC/utility.v
  /home/lch/work/miracle/chiplab/IP/MAC/bd.v
  /home/lch/work/miracle/chiplab/IP/myCPU/btb.v
  /home/lch/work/miracle/chiplab/IP/CONFREG/confreg_syn.v
  /home/lch/work/miracle/chiplab/IP/MAC/csr.v
  /home/lch/work/miracle/chiplab/IP/myCPU/dcache.v
  /home/lch/work/miracle/chiplab/IP/DEBUG/debug_sram.v
  /home/lch/work/miracle/chiplab/IP/DEBUG/debug_top.v
  /home/lch/work/miracle/chiplab/IP/myCPU/div.v
  /home/lch/work/miracle/chiplab/IP/DMA/dma.v
  /home/lch/work/miracle/chiplab/IP/MAC/dma.v
  /home/lch/work/miracle/chiplab/IP/MAC/ethernet_top.v
  /home/lch/work/miracle/chiplab/IP/myCPU/exe_stage.v
  /home/lch/work/miracle/chiplab/IP/SPI/godson_sbridge_spi.v
  /home/lch/work/miracle/chiplab/IP/myCPU/icache.v
  /home/lch/work/miracle/chiplab/IP/myCPU/id_stage.v
  /home/lch/work/miracle/chiplab/IP/myCPU/if_stage.v
  /home/lch/work/miracle/chiplab/IP/LCD/lcd_ctrl.v
  /home/lch/work/miracle/chiplab/IP/MAC/mac.v
  /home/lch/work/miracle/chiplab/IP/MAC/mac2axi.v
  /home/lch/work/miracle/chiplab/IP/MAC/mac_axi.v
  /home/lch/work/miracle/chiplab/IP/MAC/mac_top.v
  /home/lch/work/miracle/chiplab/IP/MAC/maccsr2axi.v
  /home/lch/work/miracle/chiplab/IP/MAC/macdata2axi.v
  /home/lch/work/miracle/chiplab/IP/myCPU/mem_stage.v
  /home/lch/work/miracle/chiplab/IP/myCPU/mul.v
  /home/lch/work/miracle/chiplab/IP/myCPU/my_csr.v
  /home/lch/work/miracle/chiplab/IP/myCPU/mycpu_top.v
  /home/lch/work/miracle/chiplab/IP/APB_DEV/NAND/nand.v
  /home/lch/work/miracle/chiplab/IP/APB_DEV/nand_module.v
  /home/lch/work/miracle/chiplab/IP/myCPU/perf_counter.v
  /home/lch/work/miracle/chiplab/IP/PS2/ps2_ctrl.v
  /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/raminfr.v
  /home/lch/work/miracle/chiplab/IP/MAC/rc.v
  /home/lch/work/miracle/chiplab/IP/myCPU/regfile.v
  /home/lch/work/miracle/chiplab/IP/MAC/rfifo.v
  /home/lch/work/miracle/chiplab/IP/MAC/rlsm.v
  /home/lch/work/miracle/chiplab/IP/MAC/rstc.v
  /home/lch/work/miracle/chiplab/IP/MAC/tc.v
  /home/lch/work/miracle/chiplab/IP/MAC/tfifo.v
  /home/lch/work/miracle/chiplab/IP/myCPU/tlb_entry.v
  /home/lch/work/miracle/chiplab/IP/MAC/tlsm.v
  /home/lch/work/miracle/chiplab/IP/myCPU/tools.v
  /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_receiver.v
  /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_regs.v
  /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_rfifo.v
  /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_sync_flops.v
  /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_tfifo.v
  /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_top.v
  /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_transmitter.v
  /home/lch/work/miracle/chiplab/IP/myCPU/wb_stage.v
  /home/lch/work/miracle/chiplab/chip/soc_demo/loongson/soc_top.v
}
read_ip -quiet /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux.xci
set_property used_in_synthesis false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux_impl_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux_impl_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux_clocks.xdc]

read_ip -quiet /home/lch/work/miracle/chiplab/IP/myCPU/IP/data_bank_sram/data_bank_sram.xci
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/myCPU/IP/data_bank_sram/data_bank_sram_ooc.xdc]

read_ip -quiet /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/dpram_512x32/dpram_512x32.xci
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/dpram_512x32/dpram_512x32_ooc.xdc]

read_ip -quiet /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/mig_axi_32_loongson/mig_axi_32.xci
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/mig_axi_32_loongson/mig_axi_32/user_design/constraints/mig_axi_32_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/mig_axi_32_loongson/mig_axi_32/user_design/constraints/mig_axi_32.xdc]

read_ip -quiet /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_pll_33/clk_pll_33.xci
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_pll_33/clk_pll_33_board.xdc]
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_pll_33/clk_pll_33.xdc]
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_pll_33/clk_pll_33_ooc.xdc]

read_ip -quiet /home/lch/work/miracle/chiplab/IP/myCPU/IP/tagv_sram/tagv_sram.xci
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/myCPU/IP/tagv_sram/tagv_sram_ooc.xdc]

read_ip -quiet /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_wiz_0_loongson/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_wiz_0_loongson/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_wiz_0_loongson/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_wiz_0_loongson/clk_wiz_0_late.xdc]
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_wiz_0_loongson/clk_wiz_0_ooc.xdc]

read_ip -quiet /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/axi_clock_converter_0/axi_clock_converter_0/axi_clock_converter_0.xci
set_property used_in_synthesis false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/axi_clock_converter_0/axi_clock_converter_0/axi_clock_converter_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/axi_clock_converter_0/axi_clock_converter_0/axi_clock_converter_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/axi_clock_converter_0/axi_clock_converter_0/axi_clock_converter_0_ooc.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/lch/work/miracle/chiplab/fpga/loongson/soc_up.xdc
set_property used_in_implementation false [get_files /home/lch/work/miracle/chiplab/fpga/loongson/soc_up.xdc]

set_param ips.enableIPCacheLiteLoad 1

read_checkpoint -auto_incremental -incremental /home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.srcs/utils_1/imports/synth_3/soc_top.dcp
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top soc_top -part xc7a200tfbg676-2
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file soc_top_utilization_synth.rpt -pb soc_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_3" END { }
