# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-2691731-loong-arch-mini/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a200tfbg676-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl 
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    rt::set_parameter singleFileBasedDefaultNettype false
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/lch/work/miracle/chiplab/IP/myCPU
    /home/lch/work/miracle/chiplab/chip/soc_demo/loongson
    /home/lch/work/miracle/chiplab/IP/APB_DEV/URT
    /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_pll_33
    /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_wiz_0_loongson
    /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/axi_clock_converter_0/axi_clock_converter_0/hdl
    /opt/vivado/2025.2/data/rsb/busdef
  } {
      /opt/vivado/2025.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /opt/vivado/2025.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/lch/work/miracle/chiplab/IP/myCPU
    /home/lch/work/miracle/chiplab/chip/soc_demo/loongson
    /home/lch/work/miracle/chiplab/IP/APB_DEV/URT
    /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_pll_33
    /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_wiz_0_loongson
    /home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/axi_clock_converter_0/axi_clock_converter_0/hdl
    /opt/vivado/2025.2/data/rsb/busdef
  } {
      ./.Xil/Vivado-2691731-loong-arch-mini/realtime/axi_2x1_mux_stub.v
      ./.Xil/Vivado-2691731-loong-arch-mini/realtime/data_bank_sram_stub.v
      ./.Xil/Vivado-2691731-loong-arch-mini/realtime/dpram_512x32_stub.v
      ./.Xil/Vivado-2691731-loong-arch-mini/realtime/mig_axi_32_stub.v
      ./.Xil/Vivado-2691731-loong-arch-mini/realtime/clk_pll_33_stub.v
      ./.Xil/Vivado-2691731-loong-arch-mini/realtime/tagv_sram_stub.v
      ./.Xil/Vivado-2691731-loong-arch-mini/realtime/clk_wiz_0_stub.v
      ./.Xil/Vivado-2691731-loong-arch-mini/realtime/axi_clock_converter_0_stub.v
      /home/lch/work/miracle/chiplab/IP/myCPU/addr_trans.v
      /home/lch/work/miracle/chiplab/IP/myCPU/alu.v
      /home/lch/work/miracle/chiplab/IP/APB_DEV/apb_dev_top_with_nand.v
      /home/lch/work/miracle/chiplab/IP/APB_DEV/apb_mux2.v
      /home/lch/work/miracle/chiplab/IP/AMBA/axi2apb.v
      /home/lch/work/miracle/chiplab/IP/myCPU/axi_bridge.v
      /home/lch/work/miracle/chiplab/IP/AXI/axi_interconnect_0.v
      /home/lch/work/miracle/chiplab/IP/AMBA/axi_mux_syn.v
      /home/lch/work/miracle/chiplab/IP/MAC/utility.v
      /home/lch/work/miracle/chiplab/IP/MAC/bd.v
      /home/lch/work/miracle/chiplab/IP/myCPU/btb.v
      /home/lch/work/miracle/chiplab/IP/CONFREG/confreg_syn.v
      /home/lch/work/miracle/chiplab/IP/MAC/csr.v
      /home/lch/work/miracle/chiplab/IP/myCPU/dcache.v
      /home/lch/work/miracle/chiplab/IP/DEBUG/debug_sram.v
      /home/lch/work/miracle/chiplab/IP/DEBUG/debug_top.v
      /home/lch/work/miracle/chiplab/IP/myCPU/div.v
      /home/lch/work/miracle/chiplab/IP/DMA/dma.v
      /home/lch/work/miracle/chiplab/IP/MAC/dma.v
      /home/lch/work/miracle/chiplab/IP/MAC/ethernet_top.v
      /home/lch/work/miracle/chiplab/IP/myCPU/exe_stage.v
      /home/lch/work/miracle/chiplab/IP/SPI/godson_sbridge_spi.v
      /home/lch/work/miracle/chiplab/IP/myCPU/icache.v
      /home/lch/work/miracle/chiplab/IP/myCPU/id_stage.v
      /home/lch/work/miracle/chiplab/IP/myCPU/if_stage.v
      /home/lch/work/miracle/chiplab/IP/LCD/lcd_ctrl.v
      /home/lch/work/miracle/chiplab/IP/MAC/mac.v
      /home/lch/work/miracle/chiplab/IP/MAC/mac2axi.v
      /home/lch/work/miracle/chiplab/IP/MAC/mac_axi.v
      /home/lch/work/miracle/chiplab/IP/MAC/mac_top.v
      /home/lch/work/miracle/chiplab/IP/MAC/maccsr2axi.v
      /home/lch/work/miracle/chiplab/IP/MAC/macdata2axi.v
      /home/lch/work/miracle/chiplab/IP/myCPU/mem_stage.v
      /home/lch/work/miracle/chiplab/IP/myCPU/mul.v
      /home/lch/work/miracle/chiplab/IP/myCPU/my_csr.v
      /home/lch/work/miracle/chiplab/IP/myCPU/mycpu_top.v
      /home/lch/work/miracle/chiplab/IP/APB_DEV/NAND/nand.v
      /home/lch/work/miracle/chiplab/IP/APB_DEV/nand_module.v
      /home/lch/work/miracle/chiplab/IP/myCPU/perf_counter.v
      /home/lch/work/miracle/chiplab/IP/PS2/ps2_ctrl.v
      /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/raminfr.v
      /home/lch/work/miracle/chiplab/IP/MAC/rc.v
      /home/lch/work/miracle/chiplab/IP/myCPU/regfile.v
      /home/lch/work/miracle/chiplab/IP/MAC/rfifo.v
      /home/lch/work/miracle/chiplab/IP/MAC/rlsm.v
      /home/lch/work/miracle/chiplab/IP/MAC/rstc.v
      /home/lch/work/miracle/chiplab/IP/MAC/tc.v
      /home/lch/work/miracle/chiplab/IP/MAC/tfifo.v
      /home/lch/work/miracle/chiplab/IP/myCPU/tlb_entry.v
      /home/lch/work/miracle/chiplab/IP/MAC/tlsm.v
      /home/lch/work/miracle/chiplab/IP/myCPU/tools.v
      /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_receiver.v
      /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_regs.v
      /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_rfifo.v
      /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_sync_flops.v
      /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_tfifo.v
      /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_top.v
      /home/lch/work/miracle/chiplab/IP/APB_DEV/URT/uart_transmitter.v
      /home/lch/work/miracle/chiplab/IP/myCPU/wb_stage.v
      /home/lch/work/miracle/chiplab/chip/soc_demo/loongson/soc_top.v
    }
      rt::read_vhdl -lib xpm /opt/vivado/2025.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-2691731-loong-arch-mini/realtime/soc_top_synth.xdc
    rt::sdcChecksum
    set rt::top soc_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-2691731-loong-arch-mini/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   if {[info exists rt::doParallel] && $rt::doParallel} {
     rt::async_wait "asyncParallelOpen"
     rt::parallel_close
   }
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  }
 return -code "error" $rt::result
}
