set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux/axi_2x1_mux_in_context.xdc rfile:../../../../../../../../IP/xilinx_ip/2023.2/axi_2x1_mux/axi_2x1_mux/axi_2x1_mux_in_context.xdc id:1 order:EARLY scoped_inst:u_axi_2x1_mux} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:2 order:EARLY scoped_inst:{cpu_mid/icache/data_ram_way[0].data_ram_bank[0].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:3 order:EARLY scoped_inst:{cpu_mid/icache/data_ram_way[0].data_ram_bank[1].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:4 order:EARLY scoped_inst:{cpu_mid/icache/data_ram_way[0].data_ram_bank[2].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:5 order:EARLY scoped_inst:{cpu_mid/icache/data_ram_way[0].data_ram_bank[3].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:6 order:EARLY scoped_inst:{cpu_mid/icache/data_ram_way[1].data_ram_bank[0].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:7 order:EARLY scoped_inst:{cpu_mid/icache/data_ram_way[1].data_ram_bank[1].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:8 order:EARLY scoped_inst:{cpu_mid/icache/data_ram_way[1].data_ram_bank[2].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:9 order:EARLY scoped_inst:{cpu_mid/icache/data_ram_way[1].data_ram_bank[3].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:10 order:EARLY scoped_inst:{cpu_mid/dcache/data_ram_way[0].data_ram_bank[0].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:11 order:EARLY scoped_inst:{cpu_mid/dcache/data_ram_way[0].data_ram_bank[1].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:12 order:EARLY scoped_inst:{cpu_mid/dcache/data_ram_way[0].data_ram_bank[2].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:13 order:EARLY scoped_inst:{cpu_mid/dcache/data_ram_way[0].data_ram_bank[3].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:14 order:EARLY scoped_inst:{cpu_mid/dcache/data_ram_way[1].data_ram_bank[0].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:15 order:EARLY scoped_inst:{cpu_mid/dcache/data_ram_way[1].data_ram_bank[1].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:16 order:EARLY scoped_inst:{cpu_mid/dcache/data_ram_way[1].data_ram_bank[2].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc rfile:../data_bank_sram/data_bank_sram/data_bank_sram_in_context.xdc id:17 order:EARLY scoped_inst:{cpu_mid/dcache/data_ram_way[1].data_ram_bank[3].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/dpram_512x32/dpram_512x32/dpram_512x32_in_context.xdc rfile:../../../../../../../../IP/xilinx_ip/2023.2/dpram_512x32/dpram_512x32/dpram_512x32_in_context.xdc id:18 order:EARLY scoped_inst:ETHERNET_TOP/dpram_512x32_tx} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/dpram_512x32/dpram_512x32/dpram_512x32_in_context.xdc rfile:../../../../../../../../IP/xilinx_ip/2023.2/dpram_512x32/dpram_512x32/dpram_512x32_in_context.xdc id:19 order:EARLY scoped_inst:ETHERNET_TOP/dpram_512x32_rx} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/mig_axi_32_loongson/mig_axi_32/mig_axi_32_in_context.xdc rfile:../../../../../../../../IP/xilinx_ip/2023.2/mig_axi_32_loongson/mig_axi_32/mig_axi_32_in_context.xdc id:20 order:EARLY scoped_inst:mig_axi} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_pll_33/clk_pll_33/clk_pll_33_in_context.xdc rfile:../../../../../../../../IP/xilinx_ip/2023.2/clk_pll_33/clk_pll_33/clk_pll_33_in_context.xdc id:21 order:EARLY scoped_inst:clk_pll_33} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/tagv_sram/tagv_sram/tagv_sram_in_context.xdc rfile:../tagv_sram/tagv_sram/tagv_sram_in_context.xdc id:22 order:EARLY scoped_inst:{cpu_mid/icache/tagv_ram_way[0].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/tagv_sram/tagv_sram/tagv_sram_in_context.xdc rfile:../tagv_sram/tagv_sram/tagv_sram_in_context.xdc id:23 order:EARLY scoped_inst:{cpu_mid/icache/tagv_ram_way[1].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/tagv_sram/tagv_sram/tagv_sram_in_context.xdc rfile:../tagv_sram/tagv_sram/tagv_sram_in_context.xdc id:24 order:EARLY scoped_inst:{cpu_mid/dcache/tagv_ram_way[0].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/tagv_sram/tagv_sram/tagv_sram_in_context.xdc rfile:../tagv_sram/tagv_sram/tagv_sram_in_context.xdc id:25 order:EARLY scoped_inst:{cpu_mid/dcache/tagv_ram_way[1].u}} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/IP/xilinx_ip/2023.2/clk_wiz_0_loongson/clk_wiz_0/clk_wiz_0_in_context.xdc rfile:../../../../../../../../IP/xilinx_ip/2023.2/clk_wiz_0_loongson/clk_wiz_0/clk_wiz_0_in_context.xdc id:26 order:EARLY scoped_inst:clk_pll_1} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/2023.2/system_run.runs/synth_2/.Xil/Vivado-2691731-loong-arch-mini/axi_clock_converter_0/axi_clock_converter_0/axi_clock_converter_0_in_context.xdc rfile:../axi_clock_converter_0/axi_clock_converter_0/axi_clock_converter_0_in_context.xdc id:27 order:EARLY scoped_inst:AXI_CLK_CONVERTER} [current_design]
set_property SRC_FILE_INFO {cfile:/home/lch/work/miracle/chiplab/fpga/loongson/soc_up.xdc rfile:../../../../../../soc_up.xdc id:28} [current_design]
set_property src_info {type:SCOPED_XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins u_axi_2x1_mux/INTERCONNECT_ACLK]
set_property src_info {type:SCOPED_XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins u_axi_2x1_mux/M00_AXI_ACLK]
set_property src_info {type:SCOPED_XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins u_axi_2x1_mux/S00_AXI_ACLK]
set_property src_info {type:SCOPED_XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins u_axi_2x1_mux/S01_AXI_ACLK]
set_property src_info {type:SCOPED_XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells u_axi_2x1_mux]
set_property src_info {type:SCOPED_XDC file:2 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/icache/data_ram_way[0].data_ram_bank[0].u/clka}]
set_property src_info {type:SCOPED_XDC file:2 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/icache/data_ram_way[0].data_ram_bank[0].u}]
set_property src_info {type:SCOPED_XDC file:3 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/icache/data_ram_way[0].data_ram_bank[1].u/clka}]
set_property src_info {type:SCOPED_XDC file:3 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/icache/data_ram_way[0].data_ram_bank[1].u}]
set_property src_info {type:SCOPED_XDC file:4 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/icache/data_ram_way[0].data_ram_bank[2].u/clka}]
set_property src_info {type:SCOPED_XDC file:4 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/icache/data_ram_way[0].data_ram_bank[2].u}]
set_property src_info {type:SCOPED_XDC file:5 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/icache/data_ram_way[0].data_ram_bank[3].u/clka}]
set_property src_info {type:SCOPED_XDC file:5 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/icache/data_ram_way[0].data_ram_bank[3].u}]
set_property src_info {type:SCOPED_XDC file:6 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/icache/data_ram_way[1].data_ram_bank[0].u/clka}]
set_property src_info {type:SCOPED_XDC file:6 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/icache/data_ram_way[1].data_ram_bank[0].u}]
set_property src_info {type:SCOPED_XDC file:7 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/icache/data_ram_way[1].data_ram_bank[1].u/clka}]
set_property src_info {type:SCOPED_XDC file:7 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/icache/data_ram_way[1].data_ram_bank[1].u}]
set_property src_info {type:SCOPED_XDC file:8 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/icache/data_ram_way[1].data_ram_bank[2].u/clka}]
set_property src_info {type:SCOPED_XDC file:8 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/icache/data_ram_way[1].data_ram_bank[2].u}]
set_property src_info {type:SCOPED_XDC file:9 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/icache/data_ram_way[1].data_ram_bank[3].u/clka}]
set_property src_info {type:SCOPED_XDC file:9 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/icache/data_ram_way[1].data_ram_bank[3].u}]
set_property src_info {type:SCOPED_XDC file:10 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/dcache/data_ram_way[0].data_ram_bank[0].u/clka}]
set_property src_info {type:SCOPED_XDC file:10 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/dcache/data_ram_way[0].data_ram_bank[0].u}]
set_property src_info {type:SCOPED_XDC file:11 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/dcache/data_ram_way[0].data_ram_bank[1].u/clka}]
set_property src_info {type:SCOPED_XDC file:11 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/dcache/data_ram_way[0].data_ram_bank[1].u}]
set_property src_info {type:SCOPED_XDC file:12 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/dcache/data_ram_way[0].data_ram_bank[2].u/clka}]
set_property src_info {type:SCOPED_XDC file:12 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/dcache/data_ram_way[0].data_ram_bank[2].u}]
set_property src_info {type:SCOPED_XDC file:13 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/dcache/data_ram_way[0].data_ram_bank[3].u/clka}]
set_property src_info {type:SCOPED_XDC file:13 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/dcache/data_ram_way[0].data_ram_bank[3].u}]
set_property src_info {type:SCOPED_XDC file:14 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/dcache/data_ram_way[1].data_ram_bank[0].u/clka}]
set_property src_info {type:SCOPED_XDC file:14 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/dcache/data_ram_way[1].data_ram_bank[0].u}]
set_property src_info {type:SCOPED_XDC file:15 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/dcache/data_ram_way[1].data_ram_bank[1].u/clka}]
set_property src_info {type:SCOPED_XDC file:15 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/dcache/data_ram_way[1].data_ram_bank[1].u}]
set_property src_info {type:SCOPED_XDC file:16 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/dcache/data_ram_way[1].data_ram_bank[2].u/clka}]
set_property src_info {type:SCOPED_XDC file:16 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/dcache/data_ram_way[1].data_ram_bank[2].u}]
set_property src_info {type:SCOPED_XDC file:17 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/dcache/data_ram_way[1].data_ram_bank[3].u/clka}]
set_property src_info {type:SCOPED_XDC file:17 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/dcache/data_ram_way[1].data_ram_bank[3].u}]
set_property src_info {type:SCOPED_XDC file:18 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins ETHERNET_TOP/dpram_512x32_tx/clka]
set_property src_info {type:SCOPED_XDC file:18 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins ETHERNET_TOP/dpram_512x32_tx/clkb]
set_property src_info {type:SCOPED_XDC file:18 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells ETHERNET_TOP/dpram_512x32_tx]
set_property src_info {type:SCOPED_XDC file:19 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins ETHERNET_TOP/dpram_512x32_rx/clka]
set_property src_info {type:SCOPED_XDC file:19 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins ETHERNET_TOP/dpram_512x32_rx/clkb]
set_property src_info {type:SCOPED_XDC file:19 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells ETHERNET_TOP/dpram_512x32_rx]
set_property src_info {type:SCOPED_XDC file:20 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name mig_axi/ui_clk [get_pins mig_axi/ui_clk]
set_property src_info {type:SCOPED_XDC file:20 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[0]}]
set_property src_info {type:SCOPED_XDC file:20 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[0]}]
set_property src_info {type:SCOPED_XDC file:20 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[10]}]
set_property src_info {type:SCOPED_XDC file:20 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[10]}]
set_property src_info {type:SCOPED_XDC file:20 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[11]}]
set_property src_info {type:SCOPED_XDC file:20 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[11]}]
set_property src_info {type:SCOPED_XDC file:20 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[12]}]
set_property src_info {type:SCOPED_XDC file:20 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[12]}]
set_property src_info {type:SCOPED_XDC file:20 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[1]}]
set_property src_info {type:SCOPED_XDC file:20 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[1]}]
set_property src_info {type:SCOPED_XDC file:20 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[2]}]
set_property src_info {type:SCOPED_XDC file:20 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[2]}]
set_property src_info {type:SCOPED_XDC file:20 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[3]}]
set_property src_info {type:SCOPED_XDC file:20 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[3]}]
set_property src_info {type:SCOPED_XDC file:20 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[4]}]
set_property src_info {type:SCOPED_XDC file:20 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[4]}]
set_property src_info {type:SCOPED_XDC file:20 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[5]}]
set_property src_info {type:SCOPED_XDC file:20 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[5]}]
set_property src_info {type:SCOPED_XDC file:20 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[6]}]
set_property src_info {type:SCOPED_XDC file:20 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[6]}]
set_property src_info {type:SCOPED_XDC file:20 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[7]}]
set_property src_info {type:SCOPED_XDC file:20 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[7]}]
set_property src_info {type:SCOPED_XDC file:20 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[8]}]
set_property src_info {type:SCOPED_XDC file:20 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[8]}]
set_property src_info {type:SCOPED_XDC file:20 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_addr[9]}]
set_property src_info {type:SCOPED_XDC file:20 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_addr[9]}]
set_property src_info {type:SCOPED_XDC file:20 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ba[0]}]
set_property src_info {type:SCOPED_XDC file:20 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_ba[0]}]
set_property src_info {type:SCOPED_XDC file:20 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ba[1]}]
set_property src_info {type:SCOPED_XDC file:20 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_ba[1]}]
set_property src_info {type:SCOPED_XDC file:20 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_ba[2]}]
set_property src_info {type:SCOPED_XDC file:20 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_ba[2]}]
set_property src_info {type:SCOPED_XDC file:20 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_cas_n]
set_property src_info {type:SCOPED_XDC file:20 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_cas_n]
set_property src_info {type:SCOPED_XDC file:20 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_ck_n]
set_property src_info {type:SCOPED_XDC file:20 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_ck_n]
set_property src_info {type:SCOPED_XDC file:20 line:38 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_ck_p]
set_property src_info {type:SCOPED_XDC file:20 line:39 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_ck_p]
set_property src_info {type:SCOPED_XDC file:20 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_cke]
set_property src_info {type:SCOPED_XDC file:20 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_cke]
set_property src_info {type:SCOPED_XDC file:20 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dm[0]}]
set_property src_info {type:SCOPED_XDC file:20 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dm[0]}]
set_property src_info {type:SCOPED_XDC file:20 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dm[1]}]
set_property src_info {type:SCOPED_XDC file:20 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dm[1]}]
set_property src_info {type:SCOPED_XDC file:20 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[0]}]
set_property src_info {type:SCOPED_XDC file:20 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[0]}]
set_property src_info {type:SCOPED_XDC file:20 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[10]}]
set_property src_info {type:SCOPED_XDC file:20 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[10]}]
set_property src_info {type:SCOPED_XDC file:20 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[11]}]
set_property src_info {type:SCOPED_XDC file:20 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[11]}]
set_property src_info {type:SCOPED_XDC file:20 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[12]}]
set_property src_info {type:SCOPED_XDC file:20 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[12]}]
set_property src_info {type:SCOPED_XDC file:20 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[13]}]
set_property src_info {type:SCOPED_XDC file:20 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[13]}]
set_property src_info {type:SCOPED_XDC file:20 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[14]}]
set_property src_info {type:SCOPED_XDC file:20 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[14]}]
set_property src_info {type:SCOPED_XDC file:20 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[15]}]
set_property src_info {type:SCOPED_XDC file:20 line:59 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[15]}]
set_property src_info {type:SCOPED_XDC file:20 line:60 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[1]}]
set_property src_info {type:SCOPED_XDC file:20 line:61 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[1]}]
set_property src_info {type:SCOPED_XDC file:20 line:62 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[2]}]
set_property src_info {type:SCOPED_XDC file:20 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[2]}]
set_property src_info {type:SCOPED_XDC file:20 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[3]}]
set_property src_info {type:SCOPED_XDC file:20 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[3]}]
set_property src_info {type:SCOPED_XDC file:20 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[4]}]
set_property src_info {type:SCOPED_XDC file:20 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[4]}]
set_property src_info {type:SCOPED_XDC file:20 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[5]}]
set_property src_info {type:SCOPED_XDC file:20 line:69 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[5]}]
set_property src_info {type:SCOPED_XDC file:20 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[6]}]
set_property src_info {type:SCOPED_XDC file:20 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[6]}]
set_property src_info {type:SCOPED_XDC file:20 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[7]}]
set_property src_info {type:SCOPED_XDC file:20 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[7]}]
set_property src_info {type:SCOPED_XDC file:20 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[8]}]
set_property src_info {type:SCOPED_XDC file:20 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[8]}]
set_property src_info {type:SCOPED_XDC file:20 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dq[9]}]
set_property src_info {type:SCOPED_XDC file:20 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dq[9]}]
set_property src_info {type:SCOPED_XDC file:20 line:78 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:20 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[0]}]
set_property src_info {type:SCOPED_XDC file:20 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:20 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_n[1]}]
set_property src_info {type:SCOPED_XDC file:20 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:20 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[0]}]
set_property src_info {type:SCOPED_XDC file:20 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:20 line:85 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports {ddr3_dqs_p[1]}]
set_property src_info {type:SCOPED_XDC file:20 line:86 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_odt]
set_property src_info {type:SCOPED_XDC file:20 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_odt]
set_property src_info {type:SCOPED_XDC file:20 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_ras_n]
set_property src_info {type:SCOPED_XDC file:20 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_ras_n]
set_property src_info {type:SCOPED_XDC file:20 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_reset_n]
set_property src_info {type:SCOPED_XDC file:20 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_reset_n]
set_property src_info {type:SCOPED_XDC file:20 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property IO_BUFFER_TYPE NONE [get_ports ddr3_we_n]
set_property src_info {type:SCOPED_XDC file:20 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_BUFFER_TYPE NONE [get_ports ddr3_we_n]
set_property src_info {type:SCOPED_XDC file:20 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 5 [get_pins mig_axi/clk_ref_i]
set_property src_info {type:SCOPED_XDC file:20 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins mig_axi/sys_clk_i]
set_property src_info {type:SCOPED_XDC file:20 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells mig_axi]
set_property src_info {type:SCOPED_XDC file:21 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_pll_33/clk_out1 -source [get_pins clk_pll_33/clk_in1] -edges {1 2 3} -edge_shift {0.000 10.152 20.303} [get_pins clk_pll_33/clk_out1]
set_property src_info {type:SCOPED_XDC file:21 line:2 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_pll_33/clk_out2 -source [get_pins clk_pll_33/clk_in1] -edges {1 2 3} -edge_shift {0.000 10.152 20.303} [get_pins clk_pll_33/clk_out2]
set_property src_info {type:SCOPED_XDC file:21 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins clk_pll_33/clk_in1]
set_property src_info {type:SCOPED_XDC file:21 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells clk_pll_33]
set_property src_info {type:SCOPED_XDC file:22 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/icache/tagv_ram_way[0].u/clka}]
set_property src_info {type:SCOPED_XDC file:22 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/icache/tagv_ram_way[0].u}]
set_property src_info {type:SCOPED_XDC file:23 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/icache/tagv_ram_way[1].u/clka}]
set_property src_info {type:SCOPED_XDC file:23 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/icache/tagv_ram_way[1].u}]
set_property src_info {type:SCOPED_XDC file:24 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/dcache/tagv_ram_way[0].u/clka}]
set_property src_info {type:SCOPED_XDC file:24 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/dcache/tagv_ram_way[0].u}]
set_property src_info {type:SCOPED_XDC file:25 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 20 [get_pins {cpu_mid/dcache/tagv_ram_way[1].u/clka}]
set_property src_info {type:SCOPED_XDC file:25 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells {cpu_mid/dcache/tagv_ram_way[1].u}]
set_property src_info {type:SCOPED_XDC file:26 line:1 export:INPUT save:INPUT read:READ} [current_design]
create_generated_clock -name clk_pll_1/clk_out1 -source [get_pins clk_pll_1/clk_in1] -edges {1 2 3} -edge_shift {0.000 -2.500 -5.000} [get_pins clk_pll_1/clk_out1]
set_property src_info {type:SCOPED_XDC file:26 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 10 [get_pins clk_pll_1/clk_in1]
set_property src_info {type:SCOPED_XDC file:26 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells clk_pll_1]
set_property src_info {type:SCOPED_XDC file:27 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins AXI_CLK_CONVERTER/m_axi_aclk]
set_property src_info {type:SCOPED_XDC file:27 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_PERIOD_OOC_TARGET 100 [get_pins AXI_CLK_CONVERTER/s_axi_aclk]
set_property src_info {type:SCOPED_XDC file:27 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property IS_IP_OOC_CELL true [get_cells AXI_CLK_CONVERTER]
set_property src_info {type:XDC file:28 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property CLOCK_DEDICATED_ROUTE BACKBONE [get_nets clk]
set_property src_info {type:XDC file:28 line:6 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]
set_property src_info {type:XDC file:28 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RX]
set_property src_info {type:XDC file:28 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX]
set_property src_info {type:XDC file:28 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports UART_RX2]
set_property src_info {type:XDC file:28 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports UART_TX2]
set_property src_info {type:XDC file:28 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property src_info {type:XDC file:28 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports resetn]
set_property src_info {type:XDC file:28 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led[*]}]
set_property src_info {type:XDC file:28 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led_rg0[*]}]
set_property src_info {type:XDC file:28 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {led_rg1[*]}]
set_property src_info {type:XDC file:28 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {num_a_g[*]}]
set_property src_info {type:XDC file:28 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {num_csn[*]}]
set_property src_info {type:XDC file:28 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {switch[*]}]
set_property src_info {type:XDC file:28 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_key_col[*]}]
set_property src_info {type:XDC file:28 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_key_row[*]}]
set_property src_info {type:XDC file:28 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {btn_step[*]}]
set_property src_info {type:XDC file:28 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MOSI]
set_property src_info {type:XDC file:28 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_MISO]
set_property src_info {type:XDC file:28 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CS]
set_property src_info {type:XDC file:28 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports SPI_CLK]
set_property src_info {type:XDC file:28 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {mrxd_0[*]}]
set_property src_info {type:XDC file:28 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {mtxd_0[*]}]
set_property src_info {type:XDC file:28 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports phy_rstn]
set_property src_info {type:XDC file:28 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports mtxerr_0]
set_property src_info {type:XDC file:28 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports mtxen_0]
set_property src_info {type:XDC file:28 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports mtxclk_0]
set_property src_info {type:XDC file:28 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports mrxerr_0]
set_property src_info {type:XDC file:28 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports mcoll_0]
set_property src_info {type:XDC file:28 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports mcrs_0]
set_property src_info {type:XDC file:28 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports mdc_0]
set_property src_info {type:XDC file:28 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports mdio_0]
set_property src_info {type:XDC file:28 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports mrxclk_0]
set_property src_info {type:XDC file:28 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports mrxdv_0]
set_property src_info {type:XDC file:28 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports NAND_CLE]
set_property src_info {type:XDC file:28 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports NAND_ALE]
set_property src_info {type:XDC file:28 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports NAND_RDY]
set_property src_info {type:XDC file:28 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports NAND_RD]
set_property src_info {type:XDC file:28 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports NAND_CE]
set_property src_info {type:XDC file:28 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports NAND_WR]
set_property src_info {type:XDC file:28 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[7]}]
set_property src_info {type:XDC file:28 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[6]}]
set_property src_info {type:XDC file:28 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[5]}]
set_property src_info {type:XDC file:28 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[4]}]
set_property src_info {type:XDC file:28 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[3]}]
set_property src_info {type:XDC file:28 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[2]}]
set_property src_info {type:XDC file:28 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[1]}]
set_property src_info {type:XDC file:28 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {NAND_DATA[0]}]
set_property src_info {type:XDC file:28 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports EJTAG_TRST]
set_property src_info {type:XDC file:28 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports EJTAG_TCK]
set_property src_info {type:XDC file:28 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports EJTAG_TDI]
set_property src_info {type:XDC file:28 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports EJTAG_TMS]
set_property src_info {type:XDC file:28 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports EJTAG_TDO]
set_property src_info {type:XDC file:28 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_CLK]
set_property src_info {type:XDC file:28 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_DATA]
set_property src_info {type:XDC file:28 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rst]
set_property src_info {type:XDC file:28 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_cs]
set_property src_info {type:XDC file:28 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rs]
set_property src_info {type:XDC file:28 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_wr]
set_property src_info {type:XDC file:28 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_rd]
set_property src_info {type:XDC file:28 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_bl_ctr]
set_property src_info {type:XDC file:28 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[*]}]
set_property src_info {type:XDC file:28 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_t_pen]
set_property src_info {type:XDC file:28 line:236 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_t_mosi]
set_property src_info {type:XDC file:28 line:237 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_t_clk]
set_property src_info {type:XDC file:28 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports lcd_t_cs_rst]
set_property src_info {type:XDC file:28 line:240 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 40.000 -name mrxclk_0 -waveform {0.000 20.000} [get_ports mrxclk_0]
set_property src_info {type:XDC file:28 line:241 export:INPUT save:INPUT read:READ} [current_design]
create_clock -period 40.000 -name mtxclk_0 -waveform {0.000 20.000} [get_ports mtxclk_0]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells u_axi_2x1_mux]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/icache/data_ram_way[0].data_ram_bank[0].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/dcache/data_ram_way[0].data_ram_bank[0].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/icache/data_ram_way[0].data_ram_bank[1].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/dcache/data_ram_way[0].data_ram_bank[1].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/icache/data_ram_way[0].data_ram_bank[2].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/dcache/data_ram_way[0].data_ram_bank[2].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/icache/data_ram_way[0].data_ram_bank[3].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/dcache/data_ram_way[0].data_ram_bank[3].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/icache/data_ram_way[1].data_ram_bank[0].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/dcache/data_ram_way[1].data_ram_bank[0].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/icache/data_ram_way[1].data_ram_bank[1].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/dcache/data_ram_way[1].data_ram_bank[1].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/icache/data_ram_way[1].data_ram_bank[2].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/dcache/data_ram_way[1].data_ram_bank[2].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/icache/data_ram_way[1].data_ram_bank[3].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/dcache/data_ram_way[1].data_ram_bank[3].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells ETHERNET_TOP/dpram_512x32_rx]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells ETHERNET_TOP/dpram_512x32_tx]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells mig_axi]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells clk_pll_33]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/icache/tagv_ram_way[0].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/dcache/tagv_ram_way[0].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/icache/tagv_ram_way[1].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells {cpu_mid/dcache/tagv_ram_way[1].u}]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells clk_pll_1]
set_property src_info {type:TCL file:{} line:-1 export:INPUT save:INPUT read:READ} [current_design]
set_property KEEP_HIERARCHY SOFT [get_cells AXI_CLK_CONVERTER]
